ktor {
    deployment {
        port = 8092
        port = ${?PORT}
    }
    application {
        modules = [ com.kinetix.fix.ApplicationKt.moduleWithDependencies ]
    }
}

grpc {
    port = 9105
    port = ${?GRPC_PORT}
}

database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/kinetix_fix_gateway"
    jdbcUrl = ${?DATABASE_URL}
    username = "kinetix"
    username = ${?DATABASE_USERNAME}
    password = "kinetix"
    password = ${?DATABASE_PASSWORD}
}

kafka {
    bootstrapServers = "localhost:9092"
    bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}
}
